---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  # Remove MySQL. Completely and totally.
  - sudo apt-get remove --purge 'mysql*'
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

install:
  # Install Ansible.
  - pip install ansible


script:
  # Add ansible.cfg to pick up roles path.
  # - ls
  # teste
  # - printf '[defaults]\nroles_path = /home/travis/build/amagno/ansible/' > tests/ansible.cfg
  
  #- cp -r /home/travis/build/amagno/ansible/roles/ /home/travis/build/amagno/ansible/tests/roles/

  #- ls tests/roles/

  # Check the role/playbook's syntax.
  - ansible-playbook -i ansible/invetories/travis --syntax-check --list-tasks ansible/playbook.yml

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i ansible/invetories/travis --connection=local --sudo -vvvv ansible/playbook.yml

  - php -v

  - nginx -v


  # Run the role/playbook again, checking to make sure it's idempotent.
  #- >
  #  ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
  # | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence tests: pass' && exit 0)
  # || (echo 'Idempotence tests: fail' && exit 1)

  # Request a page via Apache, to make sure Apache is running and responds.
  - "curl http://localhost/"
