- name: Install php5-fpm
  sudo: yes
  apt: pkg=php5-fpm state=latest


- name: Copy development.ini with ENV = development
  sudo: yes
  copy: src=development.ini dest=/etc/php5/fpm/php.ini force=yes backup=yes owner=root group=root mode=0644
  when: env == "development"
  notify: restart php5-fpm

- name: Copy production.ini with ENV = production
  sudo: yes
  copy: src=production.ini dest=/etc/php5/fpm/php.ini force=yes backup=yes owner=root group=root mode=0644
  when: env == "production"
  notify: restart php5-fpm
