- name: Remove all default site enabled
  sudo: yes
  shell: rm /etc/nginx/sites-enabled/*
  when: domains is defined
  ignore_errors: yes

- name: Add domains Available to Nginx Sites-Available
  sudo: yes
  template: src=vhost-nginx-template.j2 dest=/etc/nginx/sites-enabled/{{ item.name|lower() }} mode=644
  with_items: domains
  notify: restart nginx