- name: Add domains Available to Nginx Sites-Available
  sudo: yes
  template: src=vhost-nginx-template.j2 dest=/etc/nginx/sites-enabled/{{ item.server_name }} mode=0766
  with_items: domains

- name: Remove default site when domains available
  sudo: yes
  shell: rm /etc/nignx/sites-enabled/default
  when: domains is defined