---
system:
#System Packages
    packages:
       - curl
       - git
#PHP Vars
php:
    version: 5.6
    development_modules:
       - php5-xdebug
    default_modules:
       - php5-mcrypt
       - php5-mysql

#Mysql Vars Configuration
mysql:
    version: 5.6
    port: 3306
    bind_address: 0.0.0.0
    root_password: mysql123
    root_hosts: none

    #Data bases available on mysql
    data_bases:
        - testing

    #Users available on mysql
    users:
    #PHPmyadmin user
        - name: pma
          password: pmapass
          host: localhost
          privileges: "*.*:SELECT,INSERT,UPDATE,DELETE"

        - name: testing
          password: 123
          host: "%"
          privileges: "testing.*:ALL"

#NPM packages
npm:
    global_packages:
        - bower
        - gulp

#Domains Available
domains:

    - name: dev.amagno
      server_name: amagno.com.br www.amagno.com.br dev.amagno.com.br dev.amagno localhost
      root: /sites/amagno.com.br/public

    - name: phpmyadmin
      server_name: amagno.com.br www.amagno.com.br dev.amagno.com.br dev.amagno localhost
      location: /phpmyadmin
      root: /sites/phpmyadmin
