---
- hosts: all
  vars:
  # env: development or production
    env: development
  vars_files:
    - vars/vars.yml
  roles:
    - init
    - system-packages
    - nginx
    - mysql
    - php5
    - php5-cli
    - php5-fpm
    - php5-common
    - composer
    - redis-server
    - nodejs
    - npm
    - add-domains-available